<?php
define('DATA_DIR', './data');
define('MAX_LAST_POST_DIF', 3); // x seconds
define('CONFIG_PATH', DATA_DIR .'/config.json');
define('BOARDS_PATH', DATA_DIR .'/boards.json');
define('CATEGORIES_PATH', DATA_DIR .'/categories.json');
define('THREAD_ID_PATH', DATA_DIR .'/thread_id.dat');
define('STATIC_DIR', './static');
define('INDEX_JS_PATH', STATIC_DIR .'/index.js');
define('STYLE_CSS_PATH', STATIC_DIR .'/style.css');
define('DEF_APP_TITLE', 'Flatch');
define('BOARDS_DIR_NAME', 'boards');
define('BOARDS_DIR', DATA_DIR . '/'. BOARDS_DIR_NAME);
define('THREADS_DIR_NAME', 'threads');
define('SUBJECTS_FILE_NAME', 'subjects.dat');
define('BOARD_SETTING_FILE_NAME', 'setting.json');
define('DAT_LINE_SEP', '<>');
define('DAT_FILE_EXT', '.dat');
define('LIMIT_DAT_FILE_LINES', 1000);
define('RES_NAME_MIN_LEN', 0);
define('RES_NAME_MAX_LEN', 64);
define('RES_EMAIL_MIN_LEN', 0);
define('RES_EMAIL_MAX_LEN', 128);
define('RES_DATETIME_MIN_LEN', 0);
define('RES_DATETIME_MAX_LEN', 32);
define('RES_CONTENT_MIN_LEN', 1);
define('RES_CONTENT_MAX_LEN', 4096);
define('RES_SUBJECT_MIN_LEN', 1);
define('RES_SUBJECT_MAX_LEN', 128);
define('INVALID_RECORD_REG_EXP', "/[\r|\n|\t|\v|\f|\b|\a|\\|\$|\0]/");
